### ISSUE TITLE
I've read MC source. AMA.

### ISSUE THREAD

**Issue by Gaelan** [SirCmpwn/TrueCraft#48]
Unfortunately, I have read deobfuscated MC source and can't contribute. However, if you need a question about something behaves answered, feel free to ask me and I can check the source.

**Comment by SirCmpwn** [comment]
I've set up the TrueCraft wiki so that folks like you can start documenting how Minecraft works:

https://github.com/SirCmpwn/TrueCraft/wiki

A few areas you may want to focus on:

* Little details like how long wheat takes to grow
* Detailed clean-room documentation on terrain generation would be very useful, even outside of TrueCraft
* Documentation on the physics simulation

And so on. Never ever give code to clean developers - just documentation on how it works. Thanks for your help!

**Comment by robinkanters** [comment]
What are limitations to a Minecraft username (in-game name)? Only letters and numbers? Must start with a letter?

If possible, I'd like a regex that matches all possible Minecraft usernames (and is guaranteed not to exclude valid names!)

**Comment by Gaelan** [comment]
I guess this issue is defunct then.
